export default function IntellectualPropertyPolicy() {
  return (
    <div className="min-h-screen bg-black py-20 px-6">
      <div className="max-w-6xl mx-auto">
        <div className="bg-gradient-to-b from-gray-900 to-gray-950 rounded-[35px] border border-gray-800 overflow-hidden shadow-2xl">
          {/* Header */}
          <div className="relative p-10 md:p-14 border-b border-gray-800">
            <div className="absolute top-0 right-0 h-80 w-80 bg-green-500/10 blur-3xl rounded-full"></div>
            <div className="relative">
              <span className="inline-flex px-4 py-2 rounded-full text-sm font-medium bg-green-500/10 text-green-400 border border-green-500/20">
                NanoDx Legal
              </span>
              <h1 className="mt-6 text-4xl md:text-6xl font-bold text-white">
                Intellectual Property Policy
              </h1>
              <p className="mt-4 text-gray-400">
                Effective Date: July 7, 2025
              </p>
            </div>
          </div>

          {/* Content */}
          <div className="p-10 md:p-14 space-y-12 text-gray-300">

            {/* Section 1 - Introduction and Purpose */}
            <section>
              <h2 className="text-3xl font-bold text-green-400 mb-6">
                1. Introduction and Purpose
              </h2>
              <div className="bg-gray-800 rounded-3xl p-8 border border-gray-700 space-y-4">
                <p className="leading-8">
                  At NanoDx, our success is fundamentally built upon innovation, scientific discovery, and the unique intellectual capital generated by our team. This Intellectual Property (IP) Policy outlines the principles and procedures governing the creation, ownership, protection, and management of intellectual property within NanoDx. The purpose of this policy is to:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-gray-400">
                  <li><span className="font-semibold text-green-400">Protect NanoDx's Valuable Assets:</span> Safeguard the inventions, discoveries, and creative works that contribute to our competitive advantage.</li>
                  <li><span className="font-semibold text-green-400">Foster Innovation:</span> Encourage and incentivize employees, contractors, and collaborators to generate new ideas and solutions.</li>
                  <li><span className="font-semibold text-green-400">Clarify Ownership:</span> Establish clear guidelines for the ownership of IP created in the course of employment or engagement with NanoDx.</li>
                  <li><span className="font-semibold text-green-400">Ensure Compliance:</span> Adhere to all applicable laws and regulations concerning intellectual property rights.</li>
                  <li><span className="font-semibold text-green-400">Guide Responsible Use:</span> Provide a framework for the ethical and legal use of both NanoDx's and third-party intellectual property.</li>
                </ul>
              </div>
            </section>

            {/* Section 2 - Scope */}
            <section className="bg-gray-800 rounded-3xl border border-gray-700 p-8">
              <h2 className="text-3xl font-bold text-green-400 mb-6">2. Scope</h2>
              <p className="leading-8">
                This policy applies to all NanoDx employees (full-time, part-time, temporary), consultants, independent contractors, interns, and any other individuals or entities that create, contribute to, or have access to NanoDx's intellectual property, regardless of their location (including remote work).
              </p>
            </section>

            {/* Section 3 - Definition of Intellectual Property (IP) */}
            <section>
              <h2 className="text-3xl font-bold text-green-400 mb-6">
                3. Definition of Intellectual Property (IP)
              </h2>
              <div className="bg-gray-800 rounded-3xl p-8 border border-gray-700 space-y-4">
                <p className="leading-8">
                  Intellectual Property refers to creations of the mind—inventions, literary and artistic works, designs, symbols, names, and images used in commerce. For the purpose of this policy, IP includes, but is not limited to, the following categories:
                </p>
                <div className="space-y-4 mt-4">
                  <div>
                    <h3 className="font-semibold text-white mb-1">Patents:</h3>
                    <p className="text-gray-400 leading-8">Rights granted for new and useful inventions, processes, machines, articles of manufacture, or compositions of matter, or any new and useful improvements thereof. This includes utility patents, design patents, and provisional applications related to our nanomaterials, reagents, assay development processes, and diagnostic platforms.</p>
                  </div>
                  <div>
                    <h3 className="font-semibold text-white mb-1">Trade Secrets:</h3>
                    <p className="text-gray-400 leading-8">Confidential and proprietary information that provides NanoDx with a competitive advantage. This includes, but is not limited to, formulations, manufacturing processes (e.g., for gold, silica, magnetic, and fusion nanoparticles), specific protocols for functionalization, research data, unpatented discoveries, customer lists, business plans, and specialized know-how related to NanoImmunoassay Development and Immunochromatographic Assay Development.</p>
                  </div>
                  <div>
                    <h3 className="font-semibold text-white mb-1">Trademarks:</h3>
                    <p className="text-gray-400 leading-8">Words, names, symbols, logos, designs, or any combination thereof, used to identify and distinguish NanoDx's Products and Services (e.g., "NanoDx," product names, company logos).</p>
                  </div>
                  <div>
                    <h3 className="font-semibold text-white mb-1">Copyrights:</h3>
                    <p className="text-gray-400 leading-8">Rights that protect original works of authorship fixed in a tangible medium of expression. This includes software code, documentation (e.g., manuals, reports, scientific publications, marketing materials, website content), presentations, and data compilations.</p>
                  </div>
                  <div>
                    <h3 className="font-semibold text-white mb-1">Know-How:</h3>
                    <p className="text-gray-400 leading-8">Accumulated practical knowledge, experience, and skills, often unwritten, that are essential for the effective operation of NanoDx's business and development activities.</p>
                  </div>
                </div>
              </div>
            </section>

            {/* Section 4 - Ownership of Intellectual Property */}
            <section>
              <h2 className="text-3xl font-bold text-green-400 mb-6">
                4. Ownership of Intellectual Property
              </h2>
              <div className="bg-gray-800 rounded-3xl p-8 border border-gray-700 space-y-6">
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">4.1. Company Ownership of Work Product:</h3>
                  <ul className="list-disc pl-6 space-y-3 text-gray-400">
                    <li>All IP created by employees, consultants, or contractors in the course of their employment or engagement with NanoDx, or using NanoDx resources (including time, equipment, facilities, or confidential information), shall be the sole and exclusive property of NanoDx. This includes inventions, discoveries, designs, software, documentation, trade secrets, and any other intellectual property that (i) relates to NanoDx's current or demonstrably anticipated business, research, or development; (ii) results from any work performed for NanoDx; or (iii) is conceived or reduced to practice during working hours.</li>
                    <li>For employees, such IP is considered "works made for hire" where applicable by law (e.g., U.S. Copyright Act) and, to the extent it does not qualify as such, is automatically assigned to NanoDx upon its creation.</li>
                    <li>All employees and contractors are required to sign an Intellectual Property Assignment and Confidentiality Agreement (or similar agreement) as a condition of their employment or engagement, formally assigning all such IP to NanoDx and acknowledging NanoDx's ownership.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">4.2. Prior Inventions:</h3>
                  <ul className="list-disc pl-6 space-y-3 text-gray-400">
                    <li>Individuals joining NanoDx are required to disclose in writing any pre-existing intellectual property (e.g., inventions, original works) that they own or have an interest in that relates to NanoDx's business or could potentially conflict with their duties.</li>
                    <li>If any prior invention is incorporated into NanoDx's Products or Services, the individual grants NanoDx a non-exclusive, royalty-free, perpetual, worldwide license to use such prior invention.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">4.3. No Personal Claims:</h3>
                  <p className="text-gray-400 leading-8">Individuals subject to this policy agree not to assert any rights to IP created within the scope of their engagement with NanoDx or using NanoDx resources, and they waive any moral rights to the extent permissible by law.</p>
                </div>
              </div>
            </section>

            {/* Section 5 - Protection of Intellectual Property */}
            <section>
              <h2 className="text-3xl font-bold text-green-400 mb-6">
                5. Protection of Intellectual Property
              </h2>
              <div className="bg-gray-800 rounded-3xl p-8 border border-gray-700 space-y-6">
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">5.1. Identification and Disclosure:</h3>
                  <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li>All individuals are responsible for promptly disclosing any inventions, discoveries, or other potentially patentable or protectable IP to their manager and the designated IP contact within NanoDx.</li>
                    <li>Detailed and accurate records of research, development, and creation activities (e.g., lab notebooks, technical reports, data logs) must be maintained in a manner that facilitates IP protection.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">5.2. Confidentiality and Trade Secrets:</h3>
                  <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li>NanoDx's confidential information and trade secrets are critical to its competitive advantage. All individuals are obligated to maintain the strict confidentiality of NanoDx's proprietary information, both during and after their employment or engagement.</li>
                    <li>Access to confidential information is granted only on a need-to-know basis.</li>
                    <li>Appropriate security measures (physical and digital) must be followed to protect confidential data.</li>
                    <li>Non-Disclosure Agreements (NDAs) must be signed with third parties (e.g., collaborators, vendors) before sharing any confidential information.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">5.3. Formal Protection:</h3>
                  <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li>NanoDx will determine, in its sole discretion, the appropriate form of IP protection (e.g., patent filing, trademark registration, copyright registration) for its intellectual property, based on business strategy, legal advice, and competitive landscape.</li>
                    <li>All individuals are required to cooperate fully with NanoDx in obtaining and enforcing IP rights, including signing necessary documents, assisting with patent prosecution, and providing testimony if required.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">5.4. Marking and Attribution:</h3>
                  <p className="text-gray-400 leading-8">Products, documentation, and digital assets should be appropriately marked with patent pending notices, patent numbers, copyright notices (e.g., © NanoDx [Year]), and trademark symbols (™ or ®) as applicable.</p>
                </div>
              </div>
            </section>

            {/* Section 6 - Use of Third-Party Intellectual Property */}
            <section>
              <h2 className="text-3xl font-bold text-green-400 mb-6">
                6. Use of Third-Party Intellectual Property
              </h2>
              <div className="bg-gray-800 rounded-3xl p-8 border border-gray-700 space-y-6">
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">6.1. Respect for Third-Party Rights:</h3>
                  <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li>NanoDx respects the intellectual property rights of others. Individuals must not use, reproduce, distribute, or modify any third-party IP (e.g., software, images, copyrighted materials, patented technologies) without proper authorization, license, or explicit permission.</li>
                    <li>Prior to incorporating any third-party IP into NanoDx's Products, Services, or internal processes, appropriate due diligence must be conducted, and necessary licenses or agreements obtained.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">6.2. Open Source Software/Materials:</h3>
                  <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li>The use of open-source software, publicly available materials, or components governed by specific licenses (e.g., Creative Commons, MIT License) must be carefully managed to ensure compliance with the terms of those licenses and to avoid compromising NanoDx's proprietary IP.</li>
                    <li>All open-source usage must be approved by the designated NanoDx authority (e.g., CTO, Legal Department).</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Section 7 - Collaboration and External Activities */}
            <section>
              <h2 className="text-3xl font-bold text-green-400 mb-6">
                7. Collaboration and External Activities
              </h2>
              <div className="bg-gray-800 rounded-3xl p-8 border border-gray-700 space-y-6">
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">7.1. Collaborations:</h3>
                  <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li>All collaborative research, development, or service agreements with external partners (universities, research institutions, companies) must clearly define IP ownership, licensing, and confidentiality terms before any work commences or information is shared.</li>
                    <li>Such agreements must be reviewed and approved by NanoDx's legal counsel and relevant management.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold text-white text-xl mb-3">7.2. External Publications and Presentations:</h3>
                  <ul className="list-disc pl-6 space-y-2 text-gray-400">
                    <li>Employees are encouraged to participate in external scientific discourse (e.g., publishing papers, presenting at conferences). However, any such activities that involve NanoDx's proprietary information or IP must be reviewed and approved by management and/or the IP committee in advance to ensure that no valuable IP is prematurely disclosed or rights are jeopardized.</li>
                    <li>This review process is critical to ensure that patent filings precede any public disclosure that would invalidate patent novelty.</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Section 8 - Training and Awareness */}
            <section className="bg-gray-800 rounded-3xl border border-gray-700 p-8">
              <h2 className="text-3xl font-bold text-green-400 mb-6">8. Training and Awareness</h2>
              <p className="leading-8">
                NanoDx will provide training and resources to ensure all individuals understand this IP Policy, their obligations, and best practices for IP protection and responsible use.
              </p>
            </section>

            {/* Section 9 - Policy Violations and Enforcement */}
            <section className="bg-gray-800 rounded-3xl border border-gray-700 p-8">
              <h2 className="text-3xl font-bold text-green-400 mb-6">9. Policy Violations and Enforcement</h2>
              <p className="leading-8">
                Any violation of this IP Policy may result in disciplinary action, up to and including termination of employment or contract, and may also lead to legal action for damages, injunctive relief, or other remedies available under law. Individuals are encouraged to report any suspected violations of this policy.
              </p>
            </section>

            {/* Section 10 - Review and Amendments */}
            <section className="bg-gray-800 rounded-3xl border border-gray-700 p-8">
              <h2 className="text-3xl font-bold text-green-400 mb-6">10. Review and Amendments</h2>
              <p className="leading-8">
                This IP Policy will be reviewed periodically by NanoDx's management and legal counsel to ensure its effectiveness, relevance, and compliance with evolving laws and business practices. NanoDx reserves the right to amend this policy at any time.
              </p>
            </section>

            {/* Section 11 - Contact Information */}
            <section className="bg-gradient-to-r from-green-600/20 to-green-500/5 rounded-3xl border border-green-500/20 p-8">
              <h2 className="text-3xl font-bold text-green-400 mb-6">11. Contact Information</h2>
              <p className="leading-8">
                For any questions regarding this Intellectual Property Policy, or to disclose an invention or other IP, please contact:
              </p>
              <div className="mt-6 space-y-3">
                <p><span className="font-semibold text-white">NanoDx</span></p>
                <p><span className="font-semibold text-white">CSO Office</span></p>
                <p><span className="font-semibold text-white">Email:</span> admin@nanodxcorp.com</p>
                <p><span className="font-semibold text-white">Website:</span> www.nanodxcorp.com</p>
              </div>
            </section>

          </div>
        </div>
      </div>
    </div>
  );
}